export const ADD_ITEM_ACTIVITY = "ADD_ITEM_ACTIVITY";
export const EDIT_ITEM_ACTIVITY = "EDIT_ITEM_ACTIVITY";
export const DELETE_ITEM_ACTIVITY = "DELETE_ITEM_ACTIVITY";
export const PURCHASE_ACTIVITY = "PURCHASE_ACTIVITY";
export const SELL_ACTIVITY = "SELL_ACTIVITY";
